[package]
name = "rget"
version = "0.1.0"
authors = ["Mateusz Czarnecki (DemwE)"]
description = "A simple CLI tool for downloading files from the internet."
edition = "2021"

[dependencies]
clap = {version = "4.3.11", features = ["derive"]}
reqwest = {version = "0.11.18", features = ["blocking", "json", "stream"]}

